language: golang

go:
- "1.14"

script:
- go test -v ./...
- >
  FILES=$(find {cmd,internal} -name "*.go");
  if [[ -n $(gofmt -l ${FILES}) ]]; then
    gofmt -d ${FILES}
    echo 'Please run `gofmt $(find {cmd,internal} -name "*.go")`.'
    false
  fi
- >
  go mod tidy
  git diff --quiet || (
    git diff go.mod go.sum
    echo 'Please run `go mod tidy`.'
    false
  )
