language: golang

go:
- "1.14"

script:
- go test -v ./...
- >
  FILES=$(find {cmd,internal} -name "*.go");
  f(){ return $(gofmt -d ${FILES} | wc -l); };
  f || ( echo "Please run gofmt."; gofmt -d ${FILES}; false; )
