name: "pull request CI"
on: pull_request

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: "Check formatting"
    steps:
    - name: "check"
      run: |
        test -z "$(goimports -l internal cmd)"
  pwd:
    runs-on: ubuntu-latest
    name: "print pwd"
    steps:
    - name: "pwd"
      run: |
        echo $(pwd)
  mod:
    runs-on: ubuntu-latest
    name: "Check go modules"
    steps:
    - name: "check"
      run: |
        go mod tidy
        git diff --quiet
  test:
    runs-on: ubuntu-latest
    name: "Run tests"
    steps:
    - name: "check"
      run: |
        go test ./...
  vet:
    runs-on: ubuntu-latest
    name: "Verify go vet integration"
    steps:
    - name: "check"
      run: |
        go build -o . ./...
        cat << EOF > .config.json
        {}
        EOF
        go vet -vettool $(pwd)/levee -config $(pwd)/.config.json ./...
