name: "pull request CI"
on: pull_request

with-checkout: &with-checkout
  name: "checkout"
  uses: actions/checkout@v2

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: "Check formatting with goimports"
    steps:
    - *with-checkout
    - name: "check"
      run: |
        test -z "$(goimports -l internal cmd)"
  mod:
    runs-on: ubuntu-latest
    name: "Run `go mod tidy`"
    steps:
    - *with-checkout
    - name: "check"
      run: |
        go mod tidy
        git diff --quiet
  test:
    runs-on: ubuntu-latest
    name: "Run tests"
    steps:
    - *with-checkout
    - name: "check"
      run: |
        go test ./...
  vet:
    runs-on: ubuntu-latest
    name: "Verify binary integration with `go vet`"
    steps:
    - *with-checkout
    - name: "check"
      run: |
        go build -o . ./...
        cat << EOF > .config.json
        {}
        EOF
        go vet -vettool $(pwd)/levee -config $(pwd)/.config.json ./...
