# This workflow is triggered on push or pull request for the master branch.
# It verifies that the code is safe to merge.
---
name: Test

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GO_VERSION: "1.14"

jobs:
  checks:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run tests
        run: |
          go test -v ./...
